build_pipeline:
  det_option:
    name: Y5rkDetectorMNN
    mnn_path: resource/det/y5s_r_det_320x.mnn
    input_size: [320, 320]
    box_threshold: 0.5
    nms_threshold: 0.6
  vertex_option:
    name: BVTVertexMNN
    mnn_path: resource/vertex/vertex_mnet025_x96_r2.mnn
    input_size: [96, 96]
  rec_option:
      name: PPRCNNRecognitionMNN
      mnn_path: resource/rec/rec_ptocr_v3_rec_infer.mnn
      character_file: resource/rec/ppocr_keys_v1.txt
      input_size: [48, 320]
